- hosts: all
  become: yes
  tasks:
    - name: Add PHP 8.3 PPA
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes

    - name: Install dependencies
      apt:
        name: 
          - nginx
          - php8.3-fpm
          - php8.3-mysql
          - php8.3-redis
          - php8.3-xml
          - php8.3-mbstring
          - php8.3-bcmath
          - php8.3-gd
          - mysql-server
          - redis-server
          - git
          - unzip
        update_cache: yes

    - name: Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: '0755'

    - name: Install Composer globally
      command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: Remove Composer installer
      file:
        path: /tmp/composer-installer.php
        state: absent

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
