Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.define "UbuntuVM" do |subconfig|
    subconfig.vm.network :private_network, type: "dhcp"
  end 

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/setup.yml"
  end 
end  
